# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase', '>= 2.5.1'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

target 'JobSearch' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobSearch

  target 'JobSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
